use_frameworks!

platform :ios, '8.0'

target 'YWNetWorking_Example' do
  pod 'YWNetWorking', :path => '../'
  pod 'Reachability'
  target 'YWNetWorking_Tests' do
    inherit! :search_paths

    
  end
end
